name: React + TypeScript CI/CD

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    name: Execute tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cars-api-project
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: cars-api-project/package-lock.json
      - name: Instalar dependencias
        run: npm ci
      - name: Ejecutar tests
        run: npm test

  lint:
    name: Code linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cars-api-project
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: cars-api-project/package-lock.json
      - name: Instalar dependencias
        run: npm ci
      - name: Ejecutar ESLint
        run: npm run lint

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [test, lint]
    defaults:
      run:
        working-directory: cars-api-project
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: cars-api-project/package-lock.json
      - name: Instalar dependencias
        run: npm ci
      - name: Construir app React+TypeScript
        run: npm run build
      - name: Subir artefactos de build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: cars-api-project/build/
